apiVersion: v1
kind: Service
metadata:
  name: cloudnative-app-service
  namespace: cloudnative
  labels:
    app: cloudnative-app

spec:
  type: NodePort

  selector:
    app: cloudnative-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080